version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - "area:infra"
      - "type:deps"

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - "area:android"
      - "type:deps"
    open-pull-requests-limit: 5
